### ISSUE TITLE
[BUG] WC modal appears behind connectkit

### ISSUE THREAD

**Issue by shrugs** [family/connectkit#271]
**Describe the bug**

the WalletConnect modal appears behind the connectkit modal.

**To reproduce**

The default demo has this issue as well: https://docs.family.co/connectkit/try-it-out

- error on both mobile and desktop layouts

**Expected behavior**

WCM should be in front of connectkit

**Solution**

I believe it's because wallectconnect changed their css variables to a `wcm` prefix instead of `w3m` and the connectkit z-index setter code uses the old prefix:

https://github.com/family/connectkit/blob/2d0bec5d1be9314811ecf7c8adcd146e0b453e59/packages/connectkit/src/hooks/useWalletConnectModal.tsx#L20C27-L20C36

**Comment by lochie** [comment]
Fixed in https://github.com/family/connectkit/commit/c77dc936ae35834a6c9a0628c4bd26cdff676197, which will be pushed to npm soon

**Comment by shrugs** [comment]
this still occurs to me on `connectkit@1.5.1` — the new updated style is injected correctly into the head but doesn't work because the element's name is `wcm-modal`, not the old `w3m-modal` :(


<img width="653" alt="image" src="https://github.com/family/connectkit/assets/1535001/94c28ac8-22ba-4f09-b7df-c09b45816b37">

<img width="547" alt="image" src="https://github.com/family/connectkit/assets/1535001/4b01d948-4e2c-4fed-af62-f575cb0c3332">

**Comment by lochie** [comment]
whatever version of wagmi I was testing this on was still using the `<w3m-modal>` tag with the `--wcm-z-index` variable 🤦

added that tag in https://github.com/family/connectkit/commit/e2a9d2d77447143ec58822ced55b1fa66f05be8e which we'll push to npm with the next update
